#!/bin/bash
#######SBATCH --chdir /home/vlnguyen/unitraj_2024_ferrari_du_19/motionnet/

#SBATCH --ntasks=1
#######SBATCH --nodes 1
#SBATCH --cpus-per-task 6
#SBATCH --account=civil-459
#SBATCH --partition=gpu
#SBATCH --qos=civil-459
#SBATCH --gres=gpu:1
#SBATCH --mem=10G
#SBATCH --time=24:00:00

/home/vlnguyen/logs

module load gcc/11.3.0 python/3.10.4 cuda/11.8.0
source ~/venv/bin/activate
python train.py method=ptr
